name: Deploy on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy-netlify:
    name: Trigger Netlify Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Deploy Hook
        run: curl -X POST -d '{}' "${{ secrets.NETLIFYHOOK }}"

  deploy-vercel:
    name: Trigger Vercel Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCELHOOK }}"
